package com.smartcar.core;

public enum MessageId {
    OPEN_HOME_ACTIVITY, OPEN_CALIBRATION, START_CALIBRATION_SERVICE, NEXT_CALIBRATION_POSITION, FINISHED_CALIBRATION_SERVICE, STORED_CALIBRATION_POSITION, MONITOR_ALERT, START_MONITOR_SERVICE
}
