package com.smartcar.core;

public enum MessageId {
    OPEN_HOME_ACTIVITY,
    DISCOVERED_BLUETOOTH_DEVICE,
    PAIRED_BLUETOOTH_DEVICE,
    START_DISCOVERY,
    STARTED_DISCOVERY,
    GET_BLUETOOTH_STATUS,
    BLUETOOTH_STATUS,
    BACKGROUND_SERVICE_STARTED
}
